// This file was generated by Prisma, and assumes you have installed the following:
// pnpm add --save-dev prisma dotenv
import { config } from 'dotenv';
import { defineConfig } from 'prisma/config';

config({
  path: `.env.${process.env.NODE_ENV ?? 'development'}`,
});

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'npx ts-node prisma/seed.ts',
  },
  datasource: {
    url: process.env.DIRECT_URL || process.env.DATABASE_URL,
  },
});
